#ifndef HBRIDGE_CFG_H_
#define HBRIDGE_CFG_H_

#define HBRIDGE_DISABLE_PWM_ON_ENABLE_PINS											0u
#define HBRIDGE_ENABLE_PWM_ON_ENABLE_PINS											1u
#define HBRIDGE_PWM_CONTROL_ON_ENABLE_PINS											HBRIDGE_ENABLE_PWM_ON_ENABLE_PINS

#define HBRIDGE_MOTOR_1_ENABLE_PIN_NO												PD4
#define HBRIDGE_MOTOR_2_ENABLE_PIN_NO												PD5

#define HBRIDGE_MOTOR_DIRECTION_1A_PIN_NO											PD2													
#define HBRIDGE_MOTOR_DIRECTION_1B_PIN_NO											PD3
#define HBRIDGE_MOTOR_DIRECTION_2A_PIN_NO											PD6
#define HBRIDGE_MOTOR_DIRECTION_2B_PIN_NO											PD7

#endif /* HBRIDGE_CFG_H_ */
